### PR TITLE
issue #7 fixed

### PR DESCRIPTION
**Pull request by rfqu**
result file is created in current directory now

### CODE REVIEW

**Comment by alex-palevsky** [comment]
@rfqu Let me find a reviewer for this pull request, thanks for submitting it

**Comment by alex-palevsky** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rfqu looks like a fix, but what about a unit/integration test first? how do you know that it works?

**Comment by rfqu** [comment]
@yegor256 I know it works because I have run it manually. It required complex environment setup, though.

**Comment by yegor256** [comment]
@rfqu I'm sure you ran it manually, but that's not how TDD works :) **we all** have to be sure that it works, not just you on your machine. we need a unit/integration test that reproduces the problem first. then, a fix.

**Comment by rfqu** [comment]
closed as invalid.

**Comment by alex-palevsky** [comment]
@yegor256 Thank you, I have added **17 mins** to your account in payment/transaction "`000-d822db83`", time consumed: 148 hours and 8 mins; extra minutes for review comments (c=2); +17 added to your rating, current score is: [+7776](http://www.netbout.com/b/35008?open=rating)

**Pull request closed without merging**
